# Use the official Nginx image as the base image
FROM nginx:latest

# Copy your custom configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to allow incoming HTTP traffic
EXPOSE 80
